hostname: "attacker-0"
distribution: "Ubuntu"
distribution_release: "bionic"
distribution_version: "18.04"
timezone: "UTC"
default_ipv4_address: "172.28.192.242"
default_ipv6_address: "fe80::f816:3eff:fe04:4b63"
ipv4_addresses: ["172.28.192.242"]
ipv6_addresses: ["fe80::f816:3eff:fe04:4b63"]
vpn_ipv4_address: "10.237.1.238"
vpn_ipv6_address: "fe80::f816:3eff:fefa:1a96"
vpn_user: 
    name: "jthompson"
    default_ipv4_address: "172.28.195.110"
    default_ipv6_address: "fe80::f816:3eff:feea:2336"
    ipv4_addresses: ["172.28.195.110"]
    ipv6_addresses: ["fe80::f816:3eff:feea:2336"]
web_service_user:
    username: "www-data"
    uid: "33"
    gid: "33"
escalate_user:
    username: "jward"
    password: "tltUE4cB1X2V"
    uid: "1001"
    gid: "1001"
