# Samba configuration -- Managed by Ansible, please don't edit manually
# vim: ft=samba
#
# Ansible managed

[global]
  # Server information
  netbios name = internal-share
  workgroup = WORKGROUP
  server string = Fileserver %m


  # Logging
  logging = syslog

  # Authentication
  security = user
  passdb backend = tdbsam
  map to guest = never

  # Name resolution: make sure \\NETBIOS_NAME\ works
  wins support = yes
  local master = no
  domain master = no
  preferred master = yes

  # Don't load printers
  load printers = no
  printing = bsd
  printcap name = /dev/null
  disable spoolss = yes





## Shared directories
[Billing]
  comment = This share holds billing information for the company
  path = /srv/shares/Billing
  public = no
  valid users= +billing_r, +billing_w
  write list = +billing_w
  force group = billing_w
  create mode = 0664
  force create mode = 0664
  directory mode = 0775
  force directory mode = 0775

[Customers]
  comment = This share holds customer information for the company
  path = /srv/shares/Customers
  public = no
  valid users= +customers_r, +customers_w
  write list = +customers_w
  force group = customers_w
  create mode = 0664
  force create mode = 0664
  directory mode = 0775
  force directory mode = 0775

[Management]
  comment = This share is used by the company management to share files and collaborate
  path = /srv/shares/Management
  public = no
  valid users= +management_r, +management_w
  write list = +management_w
  force group = management_w
  create mode = 0664
  force create mode = 0664
  directory mode = 0775
  force directory mode = 0775

[Reports]
  comment = This share holds customer information for the company
  path = /srv/shares/Reports
  public = no
  valid users= +reports_r, +reports_w
  write list = +reports_w
  force group = reports_w
  create mode = 0664
  force create mode = 0664
  directory mode = 0775
  force directory mode = 0775

