output {
  if [@metadata][pipeline] {
    # send to elasticsearch through ingest pipeline
    elasticsearch {
      hosts => ["127.0.0.1:9200"]
      ssl => false
      index => "processed_harrison_scenario-%{type}-%{[host][name]}"
      template => "/home/ubuntu/workdir/processed_harrison_scenario/processing/logstash/processed_harrison_scenario-legacy-index-template.json"
      template_name => "processed_harrison_scenario"
      pipeline => "%{[@metadata][pipeline]}"
    }
  } else {
    # send to elasticsearch directly
    elasticsearch {
      hosts => ["127.0.0.1:9200"]
      ssl => false
      index => "processed_harrison_scenario-%{type}-%{[host][name]}"
      template => "/home/ubuntu/workdir/processed_harrison_scenario/processing/logstash/processed_harrison_scenario-legacy-index-template.json"
      template_name => "processed_harrison_scenario"
    }
  }
  if [@metadata][kyoushi][save_parsed] {
    file {
      path => "/home/ubuntu/workdir/processed_harrison_scenario/parsed/%{[host][name]}/%{[@metadata][file][relative_path]}"
    }
  }
}